### ISSUE TITLE
Determine target for trace from URI?

### ISSUE THREAD

**Issue by jbohren** [http404error/roseco#20]
It'd be great to add a link to the roseco graph for a package on http://rosindex.github.io is there some way to directly link to a specific package in roseco?

**Comment by http404error** [comment]
Yes, it's very simple. For instance, to link to the package turtlebot_arm, one would link http://http404error.github.io/roseco/graph.html?id=ros.json&focus=turtlebot_arm. Other settings can also be defined in the url, which you can see if you twiddle with the dials and knobs and hit "Link to Current Settings" (minus manually hidden packages and zoom/pan, which don't link right now).

There are a few minor issues that might be encountered along the way, though. Firstly, I don't think I'm pulling as complete a data set as you are, so some links might be dead. I'll have to look into that. Secondly, I don't know if this is the best place to permanently host roseco, but I'll be sure to let you know if that changes.

Anyways, this is exactly the sort of thing we were hoping to do with roseco, so thanks for dropping a note!

**Comment by jbohren** [comment]
Cool, thanks!
